drop table if exists s_user;


create table s_user (
	id varchar(64) generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);